//
//  TermsAndServices.swift
//  ProtoType_cookRec
//
//  Created by Aisha Ali on 11/21/21.
//

import Foundation
import UIKit

class TermsAndServices:UIViewController{
  
  
  @IBOutlet weak var TermsAndServices: UITextView!
  
  override func viewDidLoad() {
    super.viewDidLoad()
    TermsAndServices.text = """

Last Updated: November 21, 2021*
    
    * Updated to correct scrivener's errors following previous update on December 18, 2019

    Terms and Conditions of Green Chef Corporation, d/b/a Green Chef.

    Welcome and thank you for visiting GreenChef.com (“Site”) or our mobile applications (“App”) and our Terms and Conditions (“Terms”).

    BY CLICKING ON THE “COMPLETE ORDER & CHOOSE RECIPES” BUTTON, COMPLETING THE REGISTRATION PROCESS, OR ACCESSING OR USING SITE OR APP, YOU REPRESENT THAT (1) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THESE TERMS, (2) YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH COMPANY, AND (3) YOU HAVE THE AUTHORITY TO ENTER INTO THE TERMS OF USE PERSONALLY OR ON BEHALF OF COMPANY YOU HAVE NAMED AS THE USER, AND TO BIND THAT COMPANY TO THESE TERMS. THE TERM “YOU” REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE USER WHEN YOU REGISTERED ON THE SITE. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS, YOU MAY NOT ACCESS OR USE THIS SITE, THE APP OR THE OFFERINGS (AS DEFINED BELOW).

    IF YOU SUBSCRIBE TO THE SERVICE (AS DEFINED IN SECTION 5 BELOW0FOR A TERM, THEN THE TERMS WILL BE AUTOMATICALLY RENEWED FOR ADDITIONAL PERIODS OF THE SAME DURATION AS THE INITIAL TERM AT GREEN CHEF’S THEN-CURRENT FEE FOR SUCH SERVICES UNLESS YOU DECLINE TO RENEW YOUR SUBSCRIPTION IN ACCORDANCE WITH SECTIONS 5.2 AND 10.3 BELOW.

    PLEASE BE AWARE THAT SECTION 24 OF THIS AGREEMENT, BELOW, CONTAINS PROVISIONS GOVERNING HOW DISPUTES THAT YOU AND WE HAVE AGAINST EACH OTHER ARE RESOLVED, INCLUDING, WITHOUT LIMITATION, ANY DISPUTES THAT AROSE OR WERE ASSERTED PRIOR TO THE EFFECTIVE DATE OF THIS AGREEMENT. IN PARTICULAR, IT CONTAINS AN ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION. UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT: (1) YOU WILL ONLY BE PERMITTED TO PURSUE DISPUTES OR CLAIMS AND SEEK RELIEF AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING; AND (2) YOU ARE WAIVING YOUR RIGHT TO PURSUE DISPUTES OR CLAIMS AND SEEK RELIEF IN A COURT OF LAW AND TO HAVE A JURY TRIAL.

    ANY DISPUTE, CLAIM OR REQUEST FOR RELIEF RELATING IN ANY WAY TO YOUR USE OF THE SITE WILL BE GOVERNED AND INTERPRETED BY AND UNDER THE LAWS OF THE STATE OF THE STATE OF NEW YORK CONSISTENT WITH THE FEDERAL ARBITRATION ACT, WITHOUT GIVING EFFECT TO ANY PRINCIPLES THAT PROVIDE FOR THE APPLICATION OF THE LAW OF ANY OTHER JURISDICTION. THE UNITED NATIONS CONVENTION ON CONTRACTS FOR THE INTERNATIONAL SALE OF GOODS IS EXPRESSLY EXCLUDED FROM THIS AGREEMENT.

    Please note that the Site, App, the good or service offered through the Site and/or App, including, but not limited to, the Subscription Service (as defined in Section 5.1) (“Products”), the text, audio, video, graphics, or other content featured on the Site or App (“Content”); the Green Chef gift cards or gift certificates (“Gift Cards”) and the trial offers, sweepstakes, contests, or promotions (“Vouchers”);for the purposes of these Terms, are considered to be the “Offerings.” Your use of, and participation in, certain Offerings may be subject to additional terms (“Supplemental Terms”) and such Supplemental Terms will either be listed in the Terms or will be presented to you for your acceptance when you sign up to use the supplemental Offering .Supplemental Terms include Green Chef’s Privacy Policy (“Privacy Policy”), the rules applicable to the Vouchers (“Promotion Rules”) and all other applicable Green Chef operating rules, policies, and other terms and conditions or documents that may be published on the Site and/or in the App, or which you may be otherwise notified of in writing. If the Terms are inconsistent with the Supplemental Terms, these Terms shall control. The Terms and any applicable Supplemental Terms are referred to herein as the “Agreement.”

    AS FURTHER EXPLAINED IN SECTION 3, PLEASE NOTE THAT THE AGREEMENT IS SUBJECT TO CHANGE BY GREEN CHEF IN ITS SOLE DISCRETION AT ANY TIME. When changes are made, Green Chef will make a new copy of the Terms available at the Site and within the App and any new Supplemental Terms will be made available from within, or through, the Site or within the App. We will also update the “Last Updated” date at the top of the Terms. If you do not agree to any change(s) after receiving a notice of such change(s), you shall stop using the Site, the App and/or the Offerings. Otherwise, your continued use of the Site, the App and/or Offerings constitutes your acceptance of such change(s). PLEASE REGULARLY CHECK THE SITE TO VIEW THE THEN-CURRENT TERMS

    You should print a copy of these terms and conditions for future reference.

    1. INFORMATION ABOUT US
    Green Chef Corporation, d/b/a Green Chef, is a general corporation incorporated in the State of Delaware with general corporate offices at: 40 West 25th St., 7th Floor New York, NY 10010

    2. SERVICE AVAILABILITY AND YOUR STATUS
    The Site, the App, and Offerings, are intended for use by individuals in the United States of America (“Serviced Countries”). At this time, we do not accept orders from individuals outside the Serviced Countries. As such, by placing an order through our Site or App, you represent and warrant that you: (1) Are legally capable of entering into this Agreement; (2) Are at least 18 years old; (3) Are a resident of a Serviced Country; and (4) Are accessing the Site or App from a Serviced Country.

    3. MODIFICATION
    In our sole discretion, Green Chef shall have the right to change, amend, add to, remove, or supplement the Agreement (including the Privacy Policy), without notice to you; provided, however, that: changes to the procedures applicable to the resolution of disputes shall only apply to disputes which arise after the modified or additional provision is published on the Site or App.

    4. REGISTRATION
    4.1 Registering Your Account
    In order to utilize specific features on the Site and App, individuals will need to become a Registered User. For purposes of the Agreement, a “Registered User” is a user who has registered an account on the Site (“Account”) or has a valid account on the social networking service (“SNS”) through which the user has connected to the Site (each such account, a “Third-Party Account”).

    4.2 Access Through a SNS
    If you access the Site or App through a SNS as part of the functionality of the Site and/or App, you may link your Account with Third-Party Accounts, by allowing Green Chef to access your Third-Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third-Party Account. You represent that you are entitled to disclose your Third-Party Account login information to Green Chef and/or grant Green Chef access to your Third-Party Account (including, but not limited to, for use for the purposes described herein) without breach by you of any of the terms and conditions that govern your use of the applicable Third-Party Account and without obligating Green Chef to pay any fees or making Green Chef subject to any usage limitations imposed by such third-party service providers. By granting Green Chef access to any Third-Party Accounts, you understand that Green Chef may access, make available and store (if applicable) any information, data, text, software, music, sound, photographs, graphics, video, messages, tags and/or other materials accessible through the Site or App that you have provided to and stored in your Third-Party Account (“SNS Content”) so that it is available on and through the Site or App via your Account. Unless otherwise specified in the Agreement, all SNS Content shall be considered to be User Content (as defined in Section 19) for all purposes of the Agreement. Depending on the Third-Party Accounts, you choose and subject to the privacy settings that you have set in such Third-Party Accounts, personally identifiable information that you post to your Third-Party Accounts may be available on and through your Account on the Site and/or App. Please note that if a Third-Party Account or associated service becomes unavailable or Green Chef’s access to such Third-Party Account is terminated by the third-party service provider, then SNS Content will no longer be available on and through the Site and/or App. You have the ability to disable the connection between your Account and your Third-Party Accounts at any time by accessing the “Settings” section of the Site. PLEASE NOTE THAT YOUR RELATIONSHIP WITH THE THIRD-PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD-PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD-PARTY SERVICE PROVIDERS, AND GREEN CHEF DISCLAIMS ANY LIABILITY FOR PERSONALLY IDENTIFIABLE INFORMATION THAT MAY BE PROVIDED TO IT BY SUCH THIRD-PARTY SERVICE PROVIDERS IN VIOLATION OF THE PRIVACY SETTINGS THAT YOU HAVE SET IN SUCH THIRD-PARTY ACCOUNTS. Green Chef makes no effort to review any SNS Content for any purpose, including but not limited to, for accuracy, legality or non-infringement, and Green Chef is not responsible for any SNS Content.

    4.3 Registration Data
    Should you create an account with Green Chef, you agree to: (1) provide true, accurate, complete and up-to- date information, as well as updating the information as necessary; (2) maintain the security of your password and accept the risks associated with access to your account which is not authorized by you; (3) notify us as soon as possible either at help@greenchef.com or call 888-236-7295 if you believe there have been any breaches to the security of the Site, the App, or your account information; and (4) exit from your Account at the end of each session. You represent that you are (A) at least thirteen (13) years old; (B) of legal age to form a binding contract; and (C) not a person barred from using the Site or App under the laws of the United States, your place of residence or any other applicable jurisdiction. You are responsible for all activities that occur under your Account. You agree that you shall monitor your Account to restrict use by minors, and you will accept full responsibility for any unauthorized use of the Site and App by minors. You may not share your Account or password with anyone If you provide any information that is untrue, inaccurate, not current or incomplete, or Green Chef has reasonable grounds to suspect that any information you provide is untrue, inaccurate, not current or incomplete, Green Chef has the right to suspend or terminate your Account and refuse any and all current or future use of Site, App, or Offerings (or any portion thereof). You agree not to create an Account using a false identity or information, or on behalf of someone other than yourself. You agree that you shall not have more than one Account per platform or SNS at any given time. Green Chef reserves the right to remove or reclaim any usernames at any time and for any reason. You agree not to create an Account or use the Site or App if you have been previously removed by Green Chef, or if you have been previously banned from any the Site or App. You acknowledge and agree that you shall have no ownership or other property interest in your Account, and you further acknowledge and agree that all rights in and to your Account are and shall forever be owned by and inure to the benefit of Green Chef. YOU WILL BE SOLELY RESPONSIBLE FOR ALL ACCESS TO AND USE OF THE SERVICES BY ANYONE USING YOUR ACCOUNT WHETHER OR NOT SUCH ACCESS TO AND USE OF YOUR ACCOUNT IS ACTUALLY AUTHORIZED BY YOU, INCLUDING WITHOUT LIMITATION, ALL COMMUNICATIONS AND TRANSMISSIONS AND ALL OBLIGATIONS (INCLUDING, WITHOUT LIMITATION, FINANCIAL OBLIGATIONS) INCURRED THROUGH SUCH ACCESS OR USE.

    5. GREEN CHEF'S SERVICES
    5.1 Green Chef’s Subscription Service
    Our subscription service is an automatic, recurring weekly subscription to Green Chef Products (“Subscription Service” or “Service”). As part of the Service, we offer a number of subscription options that you may choose from (“Plan”). Each week you will receive a package from Green Chef (your “Meal Box”), including the contents of your chosen Plan (a specific number and type of “Meal Kits”). You can find specific details regarding your Plan and the Green Chef Service by accessing your Account details via the Site or the App.

    5.2 Auto-Renewal Feature
    THE SUBSCRIPTION SERVICE CONSISTS OF AN INITIAL CHARGE FOLLOWED BY RECURRING PERIODIC CHARGES AS AGREED TO BY YOU. BY ENTERING INTO THIS AGREEMENT, YOU ACKNOWLEDGE THAT YOUR SUBSCRIPTION HAS AN INITIAL AND RECURRING PAYMENT FEATURE AND YOU ACCEPT RESPONSIBILITY FOR ALL RECURRING CHARGES PRIOR TO DEACTIVATION. GREEN CHEF MAY SUBMIT PERIODIC CHARGES (E.G., WEEKLY) WITHOUT FURTHER AUTHORIZATION FROM YOU, UNTIL YOU PROVIDE ADVANCE NOTICE (IN COMPLIANCE WITH THE DEACTIVATION PROCEDURES IN SECTION 10.3) THAT YOU WISH TO TERMINATE THIS AUTHORIZATION OR WISH TO CHANGE YOUR PAYMENT METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE GREEN CHEF REASONABLY COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, LOG ON TO YOUR GREEN CHEF ACCOUNT, EMAIL HELP@GREENCHEF.COM OR CALL 888-236-7295. IF YOUR PAYMENT DETAILS CHANGE, YOUR CARD PROVIDER MAY PROVIDE US WITH THE UPDATED PAYMENT DETAILS. WE RESERVE THE RIGHT TO USE THESE UPDATED DETAILS FOR FUTURE CHARGES IN ORDER TO HELP PREVENT ANY INTERRUPTION TO THE DELIVERY OF SERVICE.

    ADDITIONALLY, BY SIGNING UP FOR OUR SUBSCRIPTION SERVICE YOU ARE AGREEING TO RECURRING PERIODIC PAYMENTS FOR AN INDEFINITE TIME UNTIL DEACTIVATED BY YOU OR US, ON THE SUBSCRIPTION TERMS SET OUT IN THE APPLICATION FORM YOU HAVE COMPLETED, SUBJECT TO VARIATION IN ACCORDANCE WITH THIS SECTION. YOU CAN DEACTIVATE YOUR SUBSCRIPTION AT ANY TIME, PROVIDED THAT YOU DO SO WITHIN THE APPLICABLE DEACTIVATION NOTICE PERIOD, AS DEFINED IN SECTION 10.3. YOU WILL NOT BE CHARGED FOR ANY DEACTIVATION. YOU CAN RE-SUBSCRIBE AT ANY TIME FOLLOWING YOUR DEACTIVATION, BUT WE RESERVE THE RIGHT NOT TO PERMIT RE-SUBSCRIPTION WHERE WE HAVE PREVIOUSLY ELECTED TO TERMINATE A SUBSCRIPTION BY YOU.

    FURTHERMORE, YOUR SUBSCRIPTION WILL CONTINUE INDEFINITELY UNTIL TERMINATED IN ACCORDANCE WITH THE AGREEMENT. FOLLOWING YOUR INITIAL SUBSCRIPTION PERIOD, AND AGAIN AFTER ANY SUBSEQUENT SUBSCRIPTION PERIOD, YOUR SUBSCRIPTION WILL AUTOMATICALLY COMMENCE ON THE FIRST DAY FOLLOWING THE END OF SUCH PERIOD AND CONTINUE FOR SUCCESSIVE RENEWAL PERIODS OF THE SAME LENGTH, AT THE THEN-CURRENT, NON-PROMOTIONAL SUBSCRIPTION RATE. YOU AGREE THAT YOUR ACCOUNT WILL BE SUBJECT TO THIS AUTOMATIC RENEWAL FEATURE UNLESS YOU DEACTIVATE YOUR SUBSCRIPTION. YOU CAN LOG ON TO YOUR ACCOUNT TO DEACTIVATE YOUR SUBSCRIPTION OR EMAIL HELP@GREENCHEF.COM AND WE WILL DO IT FOR YOU. ADDITIONAL DETAILS FOR DEACTIVATION PROCEDURES ARE IN SECTION 10.3 OF THIS AGREEMENT. IF YOU DEACTIVATE, YOU MAY USE YOUR SUBSCRIPTION UNTIL THE END OF YOUR THEN-CURRENT SUBSCRIPTION TERM; YOUR SUBSCRIPTION WILL NOT BE RENEWED AFTER YOUR THEN-CURRENT TERM EXPIRES. YOU WILL NOT BE ELIGIBLE FOR A PRORATED REFUND OF ANY PORTION OF THE SUBSCRIPTION FEE PAID FOR THE THEN-CURRENT SUBSCRIPTION PERIOD. BY SUBSCRIBING TO THE SERVICE, YOU AUTHORIZE GREEN CHEF TO CHARGE YOUR PAYMENT PROVIDER NOW, AND AGAIN AT THE BEGINNING OF ANY SUBSEQUENT SUBSCRIPTION PERIOD. UPON RENEWAL OF YOUR SUBSCRIPTION, IF GREEN CHEF DOES NOT RECEIVE PAYMENT FROM YOUR PAYMENT PROVIDER, (A) YOU AGREE TO PAY ALL AMOUNTS DUE ON YOUR ACCOUNT UPON DEMAND AND (B) YOU AGREE THAT GREEN CHEF MAY EITHER TERMINATE OR SUSPEND YOUR SUBSCRIPTION AND CONTINUE TO ATTEMPT TO CHARGE YOUR PAYMENT PROVIDER UNTIL PAYMENT IS RECEIVED (UPON RECEIPT OF PAYMENT, YOUR ACCOUNT WILL BE ACTIVATED AND FOR PURPOSES OF AUTOMATIC RENEWAL, YOUR NEW SUBSCRIPTION COMMITMENT PERIOD WILL BEGIN AS OF THE DAY PAYMENT WAS RECEIVED).

    6. PAYMENT AND PRICING
    6.1 Price Adjustments
    We reserve the right to adjust prices in our sole discretion, at any time and without notice to you; provided, however, that we will provide you with at least ten (10) days’ advance notice of any price changes with your specific Plan rate. Your acceptance of deliveries of the Products after such notice has been delivered to you will constitute your acceptance of such price changes, unless you cancel your subscription to the Service in accordance with this Agreement. All prices shown on the Site and/or in the App are in U.S. dollars. Any applicable taxes and other fees or charges are not included and are additional to any prices shown on the Site and/or in the App. Prices, taxes or other fees may vary geographically. The shipment of meal ingredients to you after our delivery of such notice will confirm your acceptance of such changes, unless you cancel your subscription in accordance with the Deactivation Procedures, set forth in Section 10.3.

    6.2 Plan Add-Ons
    Different features and other customized options may become available in addition to your plan, including, but not limited to, premium options, new product add-ons, and modified shipping options. These may change the price of your plan on a recurring basis. Should you have any questions about any of the options available under your plan, please visit www.greenchef.com, email help@greenchef.com or call 888-236-7295.

    6.3 Payment
    You agree to pay for all orders made from your Account in accordance with the prices and billing terms in effect at the time an order is made from your Account. You also agree to pay all applicable taxes. To make an order from an Account, you must provide valid payment information (e.g. credit card, debit card, and/or a Gift Card) through the Site or App. By placing an order through your Account, you also agree and authorize (1) the payment method(s) you provide to be immediately charged for all fees and taxes applicable to your order, (2) Green Chef to automatically charge alternative payment methods associated with your account if a primary payment method is declined or no longer available, (3) Green Chef to share payment information and instructions required to complete the payment transactions between Green Chef, our payment processors, and their third-party payment service providers (e.g., credit card transaction processing, merchant settlement, and related services), and (4) no additional notice or consent is required for the foregoing authorizations. You agree to immediately update your Account in the event of any change in your payment information. Green Chef reserves the right at any time to change its billing methods.

    7. REPLACEMENT INGREDIENTS IN MEAL KITS AND PROMOTIONAL INCLUSIONS
    Given the perishable nature of many of our ingredients, and market conditions and product supply beyond our control, we reserve the right to adjust the quantity of any ingredients in a Meal Kit, to discontinue the use of any ingredient or Product, or to substitute any ingredients or entire Meal Kits, all without notice. While we make every effort to ensure that you are provided with the very best ingredients for our Meal Kits, these switches may occasionally be required. If such a substitution is required, we will make reasonable efforts to notify you prior to shipment. If you have any issues with any substitution, or either an ingredient or a Meal Kit, please contact us at help@greenchef.com or call 888-236-7295. Additionally, please note that, on occasion, Green Chef will include products from our partners in our meal boxes which may contain some or all of the eight (8) major allergens (in addition to other ingredients). Please refer to Section 21.1 to review our allergen policy. Additionally, if you have any questions or concerns about any additional products or materials in your Meal Box, please contact Customer Care at help@greenchef.com or call 888-236-7295.

    8. GIFT CARDS
    You may purchase and/or otherwise receive Gift Cards through the Site and/or App. You must create or have an existing and valid Account with Green Chef in order to redeem a Gift Card. All Accounts are subject to the Terms in all respects. Green Chef Gift Cards may be redeemed on the Site or on the App. Redemption of Gift Cards will result in the application of a credit to your account in the amount of the Gift Card balance. Any Gift Card balance will be applied toward your purchase of Offerings until the Gift Card is depleted. Gift Cards are not redeemable for cash or credit. Notwithstanding the foregoing, Gift cards with balances of under $10.00 are redeemable for cash in the States of California, Texas, Massachusetts and Colorado. To make a request to redeem a gift card with a balance of under $10.00 in any of California, Texas, Massachusetts or Colorado, please visit email help@greenchef.com. Green Chef is not responsible for lost or stolen Gift Cards. Lost or stolen Gift Cards cannot be replaced (except as required by law). All sales of Gift Cards are final and nonrefundable. Green Chef reserves the right to refuse to honor a Gift Card where Green Chef suspects that the Gift Card was obtained fraudulently. If you suspect someone has copied or stolen your Gift Card, email help@greenchef.com immediately.

    9. VOUCHERS
    Green Chef may offer discount promotions, free/discounted trials, or other types of vouchers (“Vouchers”). In order to utilize the offer on the Voucher, users need to create an Account through the Site or App and input their information and the code found on the Voucher to redeem. If you purchase any Voucher, Voucher is deemed to have been sold at the time of payment for it. The discount found on the Voucher only lasts for the first week of your subscription plan, unless it specifically states otherwise on the Voucher or when you sign-up. Similarly, a Voucher may only be used once and may not be copied, reproduced, distributed, or published either directly or indirectly in any form or stored in data retrieval systems without our prior written approval. Additionally, Vouchers are only for first-time users of Green Chef, unless the Voucher states otherwise. Green Chef reserves the right to withdraw or deactivate any Voucher (other than one which has been purchased) for any reason, at any time. For the avoidance of doubt, and in accordance of the foregoing sentence, Green Chef reserves the right to withdraw or deactivate any of your outstanding referral credits or similar Vouchers in the event your referral code is posted to a third party website (excluding your own social media profile(s) or blogs), or if you otherwise violate this Agreement. Vouchers may only be redeemed through our Site or App, and not through any other website or method of communication. To use your Voucher, you will be required to enter its unique code at the online checkout and use of such code will be deemed to confirm your agreement to this Agreement and any special conditions attached to the Voucher.

    Pursuant to this Agreement, at the expiration of the Voucher, you agree and acknowledge that you will be billed the standard rate for your Meal Kit on a recurring, weekly basis, unless you cancel your Plan prior to the end of the Voucher period with proper, advance notice to Green Chef in accordance with this Agreement. You may cancel your Subscription Service up to seven (7) days before your first scheduled delivery that does not include the pricing found on the Voucher, pursuant to the deactivation procedures found in Section 10.3.

    As a part of the verification process, Green Chef may require you to provide additional identification information. In addition, as a part of the verification process, you authorize Green Chef to charge to your credit card a $1.00 authorization charge (or such other amount identified to customer at time of verification by Green Chef), which amount will be refunded following successful authorization.

    10. DELIVERY
    10.1 Green Chef Delivery Week
    Green Chef’s “Delivery Week” begins on Monday and runs through Sunday of the same week. The start of our Delivery Week means that new Meal Kits are available to be delivered in your Meal Box.

    10.2 Rolling Basis of Meal Selection
    You have the option of selecting the day you would like to receive your Meal Box, and, if your specific subscription allows for Meal Kit selection, you also have the option of selecting the specific Meal Kits you would like to receive, on a weekly basis. The day you select to receive your first Meal Box will be the default. In subsequent weeks, if you do not make a change, your Meal Box will arrive on the day you initially selected every week (unless you pause your order, pursuant to this Agreement, or there are extenuating circumstances, detailed in this Agreement). If you choose to have your delivery on another day for a specific week, the delivery day will change only for that week. Meal Kit selection and delivery day selection is on a rolling basis, and all selections “lock” seven days prior to the delivery day. For example, if your subscription allows for Meal Kit selection and you receive your Meal Box on Fridays, you will have to make your selection of Meal Kits you want included in your Meal Box on Friday by 11:59 PM Eastern Time, at least 7 days prior to your next delivery. Your credit card or other payment source will then be charged at midnight. Similarly, if you want to change the delivery day, you will have to make your selection seven days prior to your new delivery day.

    Please note that the specific days in which a Meal Box can be delivered varies by geographic region, and delivery on each day will not be available in all areas. If you have any questions about your area and delivery, please contact Customer Care at help@greenchef.com or call 888-236-7295.

    Green Chef does not deliver to every location, so please check with our customer service team at help@greenchef.com to see if our Meal Box is available in your area. If we currently do not deliver to your area, we cannot agree to provide you with services in accordance with our Terms, and Customers will be prohibited from paying if they have a delivery ZIP code outside of the areas where Green Chef delivers Meal Boxes. But, if you would like us to deliver to an area we do not currently cover, please let us know. We are expanding the reach of our Products and Services. We recommend that you create an account, and we will use reasonable efforts to notify you when we launch in your ZIP code.

    Green Chef uses reliable third-party delivery companies to deliver your Products. For customers that purchase perishable food products from us, each box is carefully packaged so its contents will stay adequately chilled (e.g., for meat and seafood, 40°F or cooler) until at least 10 pm on the scheduled day of delivery (modifications may be made to scheduled delivery dates during certain holidays). However, to maintain the highest quality and integrity of any food Products after delivery, we recommend that you immediately refrigerate the food items when you receive them. You should inspect your food packages to ensure the contents arrive in a cool, refrigerated condition. The best way to do this is to check the meat and fish with a food thermometer to ensure their internal temperatures are 40°F or below. If you receive a food Product containing meat or fish with an internal temperature above 40°F, you should contact our customer service and discard the item. PLEASE DO NOT RETURN ANY PERISHABLE FOOD PRODUCT UNLESS REQUESTED BY CUSTOMER SERVICE.

    10.3 Deactivation Procedures
    Please note that the ability to change an order locks seven days prior to your scheduled delivery date. Therefore, if you wish to deactivate your Account and/or cancel or change an order, you must do so before the day and time listed above for your respective delivery date. For example, if you have a scheduled delivery date on Tuesday, you have until Tuesday at 11:59 PM Eastern Time, seven days prior to your next scheduled delivery, to cancel your subscription. If you do so after the time listed for your delivery day, you will be charged and receive your Meal Box for that week, and the cancellation will take effect for the following Delivery Week. To deactivate your Account, please call Green Chef Customer Care at 888-236-7295 or email help@greenchef.com stating that you wish to terminate your account, along with your full name and registered email address.

    10.4 Pausing your Order
    During any production week, you have the option of pausing your deliveries. In order to do so, log on to your account page on the Site or App, select a particular week (by clicking on the delivery day highlighted) and then click on the “Pause Week” button. You will not be charged for any week in which your order is paused. Please note that this action cannot be taken for any scheduled order which has already “Locked,” pursuant to Section 10.2. Additionally, pausing an order shall only apply to the week in which you pause, and automatic deliveries will commence the following week, unless you choose to pause the following week, subject to the details, above.

    10.5 Delivery Specifics
    In the case of weather which inhibits the ability to make safe deliveries, or other events beyond our control that interfere with our ability to deliver your order, we will attempt to deliver your Order as soon as reasonably possible. In some cases, delivery may occur on a date other than your scheduled delivery day. If the delivery of your Meal Box is not feasible, we will cancel your delivery for the period so affected and issue you a credit, as determined in our sole discretion or refund of a part or the whole of the purchase price for that Meal Box.

    11. FORCE MAJEURE
    We will not be liable or responsible for any failure to perform, or delay the performance of, any of our obligations that is caused by events outside our reasonable control (“Force Majeure Event”). A Force Majeure Event includes any act, event, non-happening, omission or accident beyond our reasonable control and includes, but is not limited, to the following: (1) Strikes, lock-outs, or other industrial action; (2) Civil commotion, riot, invasion, terrorist attack or threat of terrorist attack, war, or threat or preparation for war; (3) Fire, explosion, storm, flood, earthquake, subsidence, epidemic, or other natural disaster; (4) Impossibility of the use of railways, shipping, aircraft, motor transport, or other means of public or private transport; (5) Impossibility of the use of public or private telecommunications networks; and (6) The acts, decrees, legislation, regulations, or restrictions of any government.

    Our performance under this Agreement is deemed to be suspended for the period that the Force Majeure Event continues, and we will have an extension of time for performance for the duration of that period. We will use our reasonable efforts to bring the Force Majeure Event to a close or to find a solution by which our obligations under this Agreement may be performed despite the Force Majeure Event.

    12. RECEIPT OF THE MATERIALS AND FOOD PREPARATION
    Green Chef uses specific materials to refrigerate perishable items and also uses third party delivery companies to deliver Meal Boxes to customers. Please note that you are responsible for reviewing the Meal Box upon delivery and inspecting all of the Products contained within for any defects or other problems upon delivery. If you are not home when your Meal Box is delivered, the Meal Box will be left at your door or in a common area. Upon the completion of your review of the Meal Box, we recommend that you place all perishables in your refrigerator to ensure the ingredients’ integrity. The risk of loss and/or damage passes to you at the time of delivery. We highly recommend that you review the USDA’s instructions on safe food handling, which can be found here. All items are solely at your risk from the time of delivery. As such, you acknowledge and agree that you are solely responsible for any preparatory steps, storage of the contents of any Meal Kits, safe washing (we recommend that all fresh produce is washed prior to inclusion in any meal), and the cooking of all the ingredients of the respective Meal Kits. We recommend that you use a thermometer to measure the temperature of any poultry, fish, or meat products that arrive in the insulated portion of the Meal Box, and, pursuant to USDA Guidelines (found here), you should utilize said thermometer to ensure that they are at (or below) 41 degrees Fahrenheit.

    Green Chef recommends that all cooking instructions found in the recipe booklet be followed, and all seafood, meats, and poultry should be cooked to the USDA’s recommended internal temperatures (165 degrees Fahrenheit for poultry; 160 degrees Fahrenheit for ground meats; 145 degrees for whole meats; and 145 degrees Fahrenheit for seafood). Green Chef recommends utilizing a food thermometer to verify internal temperatures. For more information, please see the USDA’s website, found here).

    13. RECIPE CARDS
    Additionally, please note that each Meal Kit will have a corresponding recipe card contained in the Meal Box. If your Meal Box does not contain one or more of the corresponding recipe cards, you can refer to the Site and App for the week’s recipes. If you have any questions or concerns related to the recipe cards, please contact help@greenchef.com or Customer Care at 888-236-7295.

    14. RETURN AND REFUND POLICY
    In the event that you are unhappy with any part of your Meal Box, or a specific Meal Kit, you can reach out to us at help@greenchef.com or call Customer Care at 888-236-7295. Please do so within one week of the date you received the unsatisfactory item. If related to ingredients or condition of a Meal Kit, we, at our sole discretion, may give you credit for the individual ingredient or Meal Kit, and in some situations, issue a partial or full refund for the ingredient or the Meal Kit. We reserve the right, however, to require either the return of the unsatisfactory ingredient or Meal Kit, or a photograph of such, before any partial/full refund or credit will be issued.

    15. PROPRIETARY RIGHTS
    Green Chef is the owner and operator of the Site and the App. Additionally, Green Chef is the owner of, or duly licensed to utilize, all content, features, and functionality (including, but not limited to, all information, text, graphics, software, video, and audio, and the design, selection, and arrangement thereof) published on the Site, the App, or any Offerings. The Offerings are protected by copyright, trademark, trade secret, and other intellectual property or proprietary rights laws throughout the world.

    Subject to this Agreement, Green Chef grants you a limited license to utilize the Offerings for personal, non-commercial use. Any future release, update or other addition to the Offerings shall be subject to this Agreement. Green Chef, its suppliers, and its service providers reserve all rights not granted in this Agreement.

    15.1 Trademarks
    "Green Chef," all other Green Chef marks and logos, and all titles, characters, names, graphics, and button icons are service marks, trademarks, and/or trade dress of Green Chef or otherwise proprietary to Green Chef and may not be used by you for any reason other than as expressly permitted by the Terms. All other trademarks, service marks, product names, and company names, logos, designs, or slogans appearing by and through the Offerings are the property of their respective owners and you do not acquire any ownership rights in or to such marks, logos, or names by using and/or accessing the Offerings. You will not remove, alter or obscure any copyright notice, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Offerings

    15.2 Other Content
    Except with respect to your User Content, you agree that you have no right, title, or interest in or to any Content that appears on or in the Offerings.

    15.3 Procedure for Making Claims of Copyright Infringement
    Green Chef reserves the right to terminate any end-user’s access to the Offerings where that end-user infringes upon third-party copyrights. If you believe content posted on the App or Site infringes your copyright, please provide our copyright agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on the Services of the material that you claim is infringing; (4) your address, telephone number and e-mail address; (5) a written statement that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; and (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf. Correspondence to regarding notice of claims of copyright infringement should be sent to our copyright agent help@greenchef.com.

    16. PROHIBITED USES
    You may use the Offerings only for lawful purposes and in accordance with this Agreement. You agree not to use the Offerings:

    In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries).
    For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.
    To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter”, “spam”, or any other similar solicitation.
    To impersonate or attempt to impersonate Green Chef, an employee, another user, or any other person or entity (including, without limitation, by using email addresses associated with any of the foregoing).
    To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Site or App, or which, as determined by us, may harm Green Chef or users of the Site or expose them to liability.
    Additionally, you agree not to

    Use the Site in any manner that could disable, overburden, damage, or impair the Site or interfere with any other party’s use of the Site. Use any robot, spider, or other automatic device, process, or means to access the Site for any purpose, including monitoring or copying any of the material on the Site.
    Use any manual process to monitor or copy any of the material on the Site or for any other unauthorized purpose without our prior written consent.
    Use any device, software, or routine that interferes with the proper working of the Site.
    Introduce any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.
    Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Site, the server on which the Site is stored, or any server, computer, or database connected to the Site.
    Attack the Site via a denial-of-service attack or a distributed denial-of- service attack.
    Otherwise attempt to interfere with the proper working of the Site.
    17. NON-USER THIRD PARTY CONTENT
    We may display content, advertisements, and promotions from third parties through the Site, in mailings or emails containing information regarding other companies, or with or contained within the Offerings (“Third Party Content”). The Third Party Content is not endorsed, adopted by, or controlled by Green Chef, and we make no representations or warranties of any kind regarding such Third Party Content, regarding its accuracy or completeness. You acknowledge and agree that (i) your interactions with third parties providing Third Party Content through or on the Offerings (including, but not limited to, our Site, App, social media, other Content, or Products) are solely between you and such third parties; and (ii) that it is impossible for Green Chef to monitor such materials and that you access these materials at your own risk.

    18. USER CONDUCT
    You agree that you will not violate any law, statute, regulation, intellectual property (including, but not limited to, copyright and trademarks), contractual obligations, other third party rights, or commit a tort, and that you are solely responsible for your conduct, while accessing or using the Site or App. You agree that you will abide by this Agreement and will not: (1) display personal or confidential information related to any third party, including, but not limited to, street addresses, email addresses, last names, telephone numbers, and URLs; (2) attempt to access or use another user’s account unless permitted to do so, in writing, from both the user and Green Chef; (3) engage in any behavior which is deemed to be harassment, threatening, stalking or predation of any other person; (4) make any claim, statement, or assertion, or imply, that your claim, statement, or assertion is endorsed by Green Chef without Green Chef’s express written consent; (5) engage in the commercial solicitation of other end-users; (6) collect or record end-users’ personal information without their prior written consent; (7) develop or use any third party applications that interact with any of Green Chef’s Content, the Site, or the App without our prior written consent; (8) use the Site or App in any way that prevents or inhibits other end-users from fully utilizing the Site or App, or in a way that could overburden or interfere with the functioning of the Site or App in any manner; (9) use any manual or automatic process, means, or interface (including, but not limited to robot, spider, script or, browser extension), which Green Chef has not authorized to access the Site or the App, to retrieve or index data or content; (10) decipher or reverse engineer any portion of the Site or the App that may reveal source code or bypass items designed to obstruct, limit, or stop access to any Content, specific site within the Site, or code within the Site; (11) access or attempt to access any portion or feature of the Site or App which you are not authorized to access, pursuant to this Agreement or any subsequent agreements; or (12) use the Site or the App for any illegal purpose.

    19. USER CONTENT
    Pursuant to the specifications located in this Agreement, the Site, App, or any social media platforms on which Green Chef has an official page or feed, may include, now or in the future, areas (“Interactive Areas”) that allow users to post content, including but not limited to, recipes, reviews, photos, videos, music, sound, text, graphics, code, or other materials (“User Content”). Any User Content you post or submit to us through email or other channels must, in its entirety, comply with all applicable federal, state, local and international laws and regulations, and this Agreement (including, but not limited to, the Prohibited Uses set out in Section 16 of these Terms, respectively).

    You understand and acknowledge that you are responsible for any User Content you submit or contribute through any channel or method and your use of any Interactive Areas of the Site and/or App, and you, not Green Chef, have full responsibility for such content and use, including its legality, reliability, accuracy, and appropriateness. We are not responsible or liable to any third party for the content or accuracy of any User Content posted by you or any other user of the Site. You understand and acknowledge that User Content that you share with a third party through the Site or third party platforms will be viewable by others in accordance with the privacy settings you establish.

    Any User Content you post to the Site will be considered non-confidential and non-proprietary. By providing any User Content, you represent and warrant that:(1) You own or control all rights in and to the User Content and have the right to grant the license granted below to us and our affiliates and service providers, and each of their and our respective licensees, successors, and assigns; and (2) all of your User Content does and will comply with this Agreement.

    We do not claim any ownership interest in your User Content. However, by uploading, posting or submitting User Content to the Site, the App, to our pages, e-mails, business address, or feeds on third party social media platforms (e.g., Green Chef’s Facebook page, Instagram page, or Twitter feed), you hereby: (1) grant Green Chef and its affiliates and subsidiaries a nonexclusive, royalty-free, transferable, worldwide, perpetual, irrevocable and fully sublicensable right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and publicly display your User Content; (2) represent and warrant that (a) you own and control all of the rights to the User Content or you otherwise have the lawful right to post such User Content, (b) the User Content is non-confidential and you authorize Green Chef to use such User Content for the purposes described in this Agreement, (c) the User Content is accurate and not misleading or harmful in any manner, and (d) the User Content, and your use and posting thereof, does not and will not violate this Agreement or any applicable law, rule, regulation or third party right.

    
   
"""
    
  }
  
  
}
